export const OWNER_COCKPIT_CSS = String.raw`
:root{color-scheme:light;--ink:#17201d;--muted:#66716d;--paper:#f4f2ec;--card:#fffefa;--line:#dedbd1;--accent:#275f4b;--accent2:#e1eee7;--warn:#8b4b27;--shadow:0 14px 40px rgba(30,45,38,.08);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);line-height:1.5}button,input{font:inherit}button{cursor:pointer}.shell{width:min(1180px,calc(100% - 32px));margin:auto;padding:28px 0 64px}.topbar{display:flex;justify-content:space-between;align-items:center;gap:24px;margin-bottom:28px}.eyebrow{color:var(--accent);font-size:.78rem;font-weight:750;letter-spacing:.09em;text-transform:uppercase}.brand{font-family:Georgia,serif;font-size:2rem;margin:0}.freshness{color:var(--muted);font-size:.88rem}.hero{display:grid;grid-template-columns:1.7fr 1fr;gap:18px;margin-bottom:18px}.card{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:22px;box-shadow:var(--shadow)}.hero-card{padding:30px}.hero h2{font:500 clamp(1.8rem,4vw,3.25rem)/1.08 Georgia,serif;margin:.35rem 0 1rem}.next{color:var(--accent);font-weight:700}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card h2{font:600 1.08rem/1.3 system-ui;margin:0 0 14px}.count{float:right;color:var(--muted);font-weight:500}.items{list-style:none;padding:0;margin:0}.item{padding:13px 0;border-top:1px solid var(--line)}.item:first-child{border-top:0;padding-top:0}.item-title{font-weight:700}.meta,.detail{color:var(--muted);font-size:.9rem}.pill{display:inline-block;border-radius:999px;background:var(--accent2);color:var(--accent);padding:3px 9px;font-size:.75rem;font-weight:700;margin-left:6px}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.btn{border:1px solid var(--line);border-radius:999px;background:#fff;padding:7px 12px;color:var(--ink)}.btn:hover,.btn:focus-visible{border-color:var(--accent);outline:3px solid rgba(39,95,75,.18);outline-offset:2px}.btn-primary{background:var(--accent);border-color:var(--accent);color:white}.empty{color:var(--muted);font-style:italic}.error{color:var(--warn)}.login{min-height:100vh;display:grid;place-items:center;padding:20px}.login .card{width:min(420px,100%)}label{display:block;font-weight:700;margin:18px 0 7px}input{width:100%;border:1px solid var(--line);border-radius:10px;padding:11px;background:white}#notice{position:fixed;bottom:20px;right:20px;max-width:360px;z-index:3}[hidden]{display:none!important}
@media(max-width:760px){.hero,.grid{grid-template-columns:1fr}.shell{width:min(100% - 20px,1180px);padding-top:18px}.topbar{align-items:flex-start}.card,.hero-card{padding:18px}.brand{font-size:1.6rem}}
@media(prefers-reduced-motion:no-preference){.card{transition:transform .16s ease}.card:hover{transform:translateY(-1px)}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
`;

export const OWNER_COCKPIT_LOGIN_HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Andrea owner sign in</title><link rel="stylesheet" href="/assets/cockpit.css"></head><body><main class="login"><section class="card" aria-labelledby="login-title"><p class="eyebrow">Private owner access</p><h1 id="login-title" class="brand">Andrea</h1><p>Enter the local cockpit secret. Tailnet access alone is not sufficient.</p><form method="post" action="/auth/login"><label for="secret">Cockpit secret</label><input id="secret" name="secret" type="password" required autocomplete="current-password"><div class="actions"><button class="btn btn-primary" type="submit">Sign in</button></div></form></section></main></body></html>`;

export const OWNER_COCKPIT_HTML = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f4f2ec"><title>Andrea owner cockpit</title><link rel="stylesheet" href="/assets/cockpit.css"></head><body><main class="shell" id="main"><header class="topbar"><div><p class="eyebrow">Personal command center</p><h1 class="brand">Andrea</h1></div><div class="freshness" id="freshness" role="status">Loading…</div></header><section class="hero" aria-label="Today"><article class="card hero-card"><p class="eyebrow">Best next move</p><h2 id="best-next">Loading your context…</h2><p class="detail" id="best-why"></p></article><article class="card"><h2>Today <span class="count" id="today-count"></span></h2><ul class="items" id="today"></ul></article></section><section class="grid" aria-label="Personal context"><article class="card"><h2>Open loops <span class="count" id="threads-count"></span></h2><ul class="items" id="threads"></ul></article><article class="card"><h2>Goals <span class="count" id="goals-count"></span></h2><ul class="items" id="goals"></ul></article><article class="card"><h2>Waiting for approval <span class="count" id="approvals-count"></span></h2><ul class="items" id="approvals"></ul></article><article class="card"><h2>Recent outcomes <span class="count" id="outcomes-count"></span></h2><ul class="items" id="outcomes"></ul></article></section></main><div id="notice" class="card" role="status" aria-live="polite" hidden></div><script src="/assets/cockpit.js" defer></script></body></html>`;

export const OWNER_COCKPIT_JS = String.raw`
const $=id=>document.getElementById(id);let csrf='';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(message,error=false){const n=$('notice');n.textContent=message;n.classList.toggle('error',error);n.hidden=false;setTimeout(()=>n.hidden=true,4200)}
function empty(text){return '<li class="empty">'+esc(text)+'</li>'}
function item(title,detail,meta,actions=''){return '<li class="item"><div class="item-title">'+esc(title)+'</div>'+(detail?'<div class="detail">'+esc(detail)+'</div>':'')+(meta?'<div class="meta">'+esc(meta)+'</div>':'')+actions+'</li>'}
function controls(kind,id,state){const next=state==='paused'?'active':'paused';return '<div class="actions"><button class="btn" data-kind="'+kind+'" data-id="'+esc(id)+'" data-state="'+next+'">'+(next==='paused'?'Pause':'Resume')+'</button></div>'}
async function mutate(path,body){const res=await fetch(path,{method:'POST',headers:{'content-type':'application/json','x-csrf-token':csrf},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data}
async function load(){const res=await fetch('/api/v1/snapshot');if(res.status===401){location.href='/login';return}const d=await res.json();if(!res.ok)throw new Error(d.error||'Could not load Andrea');csrf=d.csrfToken;$('freshness').textContent='Updated '+new Date(d.generatedAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'});$('best-next').textContent=d.focus.title;$('best-why').textContent=d.focus.reason;$('today').innerHTML=d.today.length?d.today.map(x=>item(x.title,x.detail,x.meta)).join(''):empty('Nothing urgent is competing for your attention.');$('today-count').textContent=d.today.length;$('threads').innerHTML=d.threads.length?d.threads.map(x=>item(x.title,x.nextAction,x.status,controls('thread',x.id,x.status))).join(''):empty('No active open loops.');$('threads-count').textContent=d.threads.length;$('goals').innerHTML=d.goals.length?d.goals.map(x=>item(x.title,x.nextAction,x.priority,controls('goal',x.id,x.status))).join(''):empty('No active goals.');$('goals-count').textContent=d.goals.length;$('approvals').innerHTML=d.approvals.length?d.approvals.map(x=>item(x.summary,'Expires '+(x.expiresAt?new Date(x.expiresAt).toLocaleString():'when context changes'),x.actionClass,'<div class="actions"><button class="btn btn-primary" data-approve="'+esc(x.id)+'" data-summary="'+esc(x.summary)+'">Review and approve</button></div>')).join(''):empty('No actions are waiting for approval.');$('approvals-count').textContent=d.approvals.length;$('outcomes').innerHTML=d.outcomes.length?d.outcomes.map(x=>item(x.summary,x.nextAction,x.status)).join(''):empty('Verified outcomes will appear here.');$('outcomes-count').textContent=d.outcomes.length}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.kind){await mutate('/api/v1/reversible-state',{kind:b.dataset.kind,id:b.dataset.id,state:b.dataset.state});show('Updated.');await load()}else if(b.dataset.approve){const summary=b.dataset.summary;if(!confirm('Approve this exact staged action?\n\n'+summary))return;await mutate('/api/v1/approvals/'+encodeURIComponent(b.dataset.approve)+'/confirm',{summary,confirmation:'APPROVE'});show('Approval recorded. Andrea will revalidate before execution.');await load()}}catch(err){show(err.message,true)}});load().catch(err=>show(err.message,true));
`;
